[package]
name = "png2rex"
version = "0.1.0"
authors = ["Herbert Wolverson <herberticus@gmail.com>"]
edition = "2018"

[dependencies]
bracket-lib = "0.8"
image = { version = "0.23.12", default-features = false, features = ["png"] }
colored = "2.0.0"
